language: php
sudo: false
php:
- '5.6'
cache:
  directories:
  - node_modules
env:
  global:
  - GIT_COMMITTER_NAME=torounit
  - GIT_COMMITTER_EMAIL=mail@torounit.com
  - GIT_AUTHOR_NAME=torounit
  - GIT_AUTHOR_EMAIL=mail@torounit.com
  - secure: SUI4UV6c8i2/9P0mGdFPO10+zJtnaAsU82SyDhst4O+r0z7bUIUbM8s0NpWw0StaY29OMFfUcZZ347ujdA5JHj8AAaYaKbVc6WQyvIpTICNk6c/nnz2dmY4na3mrOwtwSSDCYqN7FofQtynUYCQrnvbo3fqO5T6oFJxKITrmEuV3zXfqE8k/nS1loxDXe8pOZEVLbYrQx/zLvA/J5o6hg8PS+SHaMES4PbTss/g2BwRxjBZEVdUcJjwtGxJualV1Fo37D1JJKLGHrGGoSAzqtKbUNDKuuHz1rgztbVoXhDk+sHpCrAB9yeD1H3wRF6gv3Pa3y0vT5eU4MwneHKoKMfodbSDUTYVWIcjp1INaOT5LGZV7gQJmUojqjxBspUbMi8pBmsGNG4hZqZd1RME2I2hoLxnvHUqX9LU7OoUVHo8bOM1+daxRsQQxMbLaqkgB1OeTqRYYeZmLxnCXQPwtQ3RizfD8m5eq7OkVwBgnbIFoD3HbEaXB5m1ksmIyHxAuhvFaOf9EBcqvfZvY3a5fnJ2TVcUfQlos0UsmNOyv2Qwbmgfm3v0p442Vy4aTett+VTX0ZDNGd4OtS0DdEyRJ7Qtr3c0k7oWmTUlwMneBhiYXVGAGwxUCL2YjCAz0pEO8UrJlRKxDq8uk5g8xaXCDTMp/hbuHex66zALVuqB5sHo=
before_script:
- nvm install 6
- npm install
- npm run build
- composer install
script:
- find . -path './vendor' -prune -o -name '*.php' -exec php -lf {} \;
after_success:
- bash ./bin/deploy.sh
