language: php
sudo: false
php:
- '5.6'
cache:
  directories:
  - node_modules
env:
  global:
  - GIT_COMMITTER_NAME=torounit
  - GIT_COMMITTER_EMAIL=mail@torounit.com
  - GIT_AUTHOR_NAME=torounit
  - GIT_AUTHOR_EMAIL=mail@torounit.com

before_script:
- nvm install 6
- npm install
- npm run build
- composer install
script:
- find . -path './vendor' -prune -o -name '*.php' -exec php -lf {} \;
after_success:
- bash ./bin/deploy.sh
